# Generated by Django 3.2.5 on 2021-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(default='https://www.google.co.in/', max_length=255),
        ),
    ]
