# Generated by Django 3.2.5 on 2021-07-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_slider_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
    ]
