# Generated by Django 3.2.5 on 2021-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0006_auto_20210715_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='photo',
            field=models.ImageField(upload_to='media/ytubers/%Y/%m'),
        ),
    ]
