# Generated by Django 3.2.5 on 2021-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0009_alter_youtuber_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='video_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
