# Generated by Django 3.2.5 on 2021-07-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttuber',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
