# Generated by Django 3.2.5 on 2021-07-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tubers', '0002_alter_contacttuber_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttuber',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
